version: "3.4"

services:
  db:
    image: postgres:latest
    container_name: shotgame-db
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    container_name: shotgame-redis
    restart: always
    image: redis
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
    driver: local

networks:
  default:
    external: true
    name: main